# Generated by Django 5.1.3 on 2025-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_price', models.FloatField()),
                ('usd_rate', models.FloatField()),
                ('inflation_rate', models.FloatField()),
                ('gold_price_usd', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('festivals', models.IntegerField()),
                ('nepse_index', models.FloatField()),
                ('model_used', models.CharField(default='Linear Regression', max_length=100)),
                ('model_accuracy', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Predictions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
